/**
 * Facilitator Session Note: form schema v1 (fn-v1)
 * Shared by the Apps Script backend (copy as FnSchema.gs) and the PWA (load as a script).
 * Stored values are always the English codes below. Hindi and Marathi labels are DRAFTS
 * pending back-translation (Prajakta, Devanand) before release.
 */
var FN_SCHEMA = (function () {
  function o(v, en, hi, mr) { return { v: v, en: en, hi: hi, mr: mr }; }
  var SCALE = { min: 1, max: 5 };
  return {
    version: 'fn-v1',
    textMax: 300,
    sections: [
      { id: 'A', en: 'Session basics', hi: 'सत्र की बुनियादी जानकारी', mr: 'सत्राची मूलभूत माहिती' },
      { id: 'B', en: 'Before the session', hi: 'सत्र से पहले', mr: 'सत्रापूर्वी' },
      { id: 'C', en: 'During the session', hi: 'सत्र के दौरान', mr: 'सत्रादरम्यान' },
      { id: 'D', en: 'Possible bias', hi: 'संभावित पूर्वाग्रह', mr: 'संभाव्य पूर्वग्रह' },
      { id: 'E', en: 'Safeguarding', hi: 'सुरक्षा', mr: 'सुरक्षा' },
      { id: 'F', en: 'Your read', hi: 'आपका आकलन', mr: 'तुमचे मूल्यांकन' }
    ],
    // A1 (session link) and facilitator_code are filled by the app, never typed.
    fields: [
      { id: 'role', q: 'A2', sec: 'A', type: 'single', required: true,
        en: 'Your role in this session', hi: 'इस सत्र में आपकी भूमिका', mr: 'या सत्रातील तुमची भूमिका',
        options: [o('lead', 'Lead facilitator', 'मुख्य फैसिलिटेटर', 'मुख्य फॅसिलिटेटर'), o('co', 'Co-facilitator', 'सह-फैसिलिटेटर', 'सह-फॅसिलिटेटर'), o('observer', 'Observer or volunteer', 'पर्यवेक्षक या स्वयंसेवक', 'निरीक्षक किंवा स्वयंसेवक')] },
      { id: 'respondent_group', q: 'A3', sec: 'A', type: 'single', required: true,
        en: 'Who were the respondents?', hi: 'उत्तरदाता कौन थे?', mr: 'उत्तरदाते कोण होते?',
        options: [o('students', 'Students', 'विद्यार्थी', 'विद्यार्थी'), o('parents', 'Parents', 'अभिभावक', 'पालक'), o('teachers', 'Teachers', 'शिक्षक', 'शिक्षक'), o('staff', 'School staff', 'स्कूल स्टाफ', 'शाळेचे कर्मचारी'), o('mixed', 'Mixed', 'मिश्रित', 'मिश्र')] },
      { id: 'headcount_band', q: 'A4', sec: 'A', type: 'single', required: true,
        en: 'Roughly how many were present?', hi: 'लगभग कितने लोग उपस्थित थे?', mr: 'साधारण किती लोक उपस्थित होते?',
        options: [o('1-10', '1–10', '1–10', '1–10'), o('11-25', '11–25', '11–25', '11–25'), o('26-50', '26–50', '26–50', '26–50'), o('51+', '51 or more', '51 या अधिक', '51 किंवा अधिक')] },
      { id: 'gender_mix', q: 'A5', sec: 'A', type: 'single', required: true,
        en: 'Gender mix in the room', hi: 'कमरे में लिंग अनुपात', mr: 'खोलीतील लिंग प्रमाण',
        options: [o('mostly_women', 'Mostly women', 'अधिकतर महिलाएँ', 'बहुतेक महिला'), o('even', 'Roughly even', 'लगभग बराबर', 'साधारण समान'), o('mostly_men', 'Mostly men', 'अधिकतर पुरुष', 'बहुतेक पुरुष')] },
      { id: 'forms_collected', q: 'A6', sec: 'A', type: 'int', required: true, min: 0, max: 500,
        en: 'Forms collected', hi: 'एकत्र किए गए फ़ॉर्म', mr: 'जमा केलेले फॉर्म' },
      { id: 'forms_flagged', q: 'A6', sec: 'A', type: 'int', required: true, min: 0, max: 500,
        en: 'Forms you think are incomplete or invalid', hi: 'अधूरे या अमान्य लगने वाले फ़ॉर्म', mr: 'अपूर्ण किंवा अवैध वाटणारे फॉर्म' },
      { id: 'form_language', q: 'A7', sec: 'A', type: 'single', required: true,
        en: 'Language of the printed form', hi: 'छपे फ़ॉर्म की भाषा', mr: 'छापील फॉर्मची भाषा',
        options: [o('en', 'English', 'अंग्रेज़ी', 'इंग्रजी'), o('hi', 'Hindi', 'हिंदी', 'हिंदी'), o('mr', 'Marathi', 'मराठी', 'मराठी'), o('other', 'Other', 'अन्य', 'इतर')] },
      { id: 'readout_language', q: 'A8', sec: 'A', type: 'single', required: true,
        en: 'Language used to read questions aloud', hi: 'प्रश्न पढ़कर सुनाने की भाषा', mr: 'प्रश्न मोठ्याने वाचण्याची भाषा',
        options: [o('none', 'Not read aloud', 'पढ़कर नहीं सुनाया', 'वाचून दाखवले नाही'), o('en', 'English', 'अंग्रेज़ी', 'इंग्रजी'), o('hi', 'Hindi', 'हिंदी', 'हिंदी'), o('mr', 'Marathi', 'मराठी', 'मराठी'), o('ur', 'Urdu', 'उर्दू', 'उर्दू'), o('other', 'Other', 'अन्य', 'इतर')] },
      { id: 'session_start', q: 'A9', sec: 'A', type: 'time', required: true,
        en: 'Session start time', hi: 'सत्र शुरू होने का समय', mr: 'सत्र सुरू होण्याची वेळ' },
      { id: 'session_end', q: 'A9', sec: 'A', type: 'time', required: true,
        en: 'Session end time', hi: 'सत्र समाप्त होने का समय', mr: 'सत्र संपण्याची वेळ' },
      { id: 'entry_mode', q: 'A10', sec: 'A', type: 'single', required: true,
        en: 'Are you filling this right after the session, or later from memory?', hi: 'क्या आप यह सत्र के तुरंत बाद भर रहे हैं, या बाद में याद से?', mr: 'तुम्ही हे सत्रानंतर लगेच भरत आहात की नंतर आठवणीतून?',
        options: [o('live', 'Right after the session', 'सत्र के तुरंत बाद', 'सत्रानंतर लगेच'), o('recalled', 'Later, from memory', 'बाद में, याद से', 'नंतर, आठवणीतून')] },
      { id: 'venue', q: 'B1', sec: 'B', type: 'single', required: true,
        en: 'Where was the session held?', hi: 'सत्र कहाँ हुआ?', mr: 'सत्र कुठे झाले?',
        options: [o('classroom', 'Classroom', 'कक्षा', 'वर्ग'), o('hall', 'Hall', 'हॉल', 'सभागृह'), o('office', 'Office', 'कार्यालय', 'कार्यालय'), o('outdoors', 'Outdoors', 'बाहर', 'बाहेर'), o('other', 'Other', 'अन्य', 'इतर')] },
      { id: 'privacy_score', q: 'B2', sec: 'B', type: 'scale', required: true, scale: SCALE,
        en: "Could respondents see each other's answers?", hi: 'क्या उत्तरदाता एक-दूसरे के उत्तर देख सकते थे?', mr: 'उत्तरदात्यांना एकमेकांची उत्तरे दिसू शकत होती का?',
        anchors: { en: ['Fully private', 'Easily seen'], hi: ['पूरी तरह निजी', 'आसानी से दिखते थे'], mr: ['पूर्णपणे खाजगी', 'सहज दिसत होती'] } },
      { id: 'others_present', q: 'B3', sec: 'B', type: 'multi', required: true, exclusive: 'none',
        en: 'Who else was in the room?', hi: 'कमरे में और कौन था?', mr: 'खोलीत आणखी कोण होते?',
        options: [o('none', 'Nobody else', 'कोई नहीं', 'कोणीही नाही'), o('teacher', 'Teacher', 'शिक्षक', 'शिक्षक'), o('principal', 'Principal or head', 'प्रधानाचार्य या प्रमुख', 'मुख्याध्यापक किंवा प्रमुख'), o('staff', 'Other staff', 'अन्य स्टाफ', 'इतर कर्मचारी'), o('family', 'Family members', 'परिवार के सदस्य', 'कुटुंबातील सदस्य'), o('others', 'Others', 'अन्य', 'इतर')] },
      { id: 'start_delay', q: 'B4', sec: 'B', type: 'single', required: true,
        en: 'Did the session start on time?', hi: 'क्या सत्र समय पर शुरू हुआ?', mr: 'सत्र वेळेवर सुरू झाले का?',
        options: [o('on_time', 'On time', 'समय पर', 'वेळेवर'), o('up_to_15', 'Up to 15 min late', '15 मिनट तक देर', '15 मिनिटांपर्यंत उशीर'), o('over_15', 'More than 15 min late', '15 मिनट से अधिक देर', '15 मिनिटांपेक्षा जास्त उशीर')] },
      { id: 'noise_score', q: 'C1', sec: 'C', type: 'scale', required: true, scale: SCALE,
        en: 'Noise and disturbance', hi: 'शोर और व्यवधान', mr: 'आवाज आणि व्यत्यय',
        anchors: { en: ['Quiet', 'Very disruptive'], hi: ['शांत', 'बहुत व्यवधान'], mr: ['शांत', 'खूप व्यत्यय'] } },
      { id: 'interruptions', q: 'C2', sec: 'C', type: 'multi', required: true, exclusive: 'none',
        en: 'Interruptions', hi: 'रुकावटें', mr: 'अडथळे',
        options: [o('none', 'None', 'कोई नहीं', 'काहीही नाही'), o('movement', 'People entering or leaving', 'लोगों का आना-जाना', 'लोकांची ये-जा'), o('phones', 'Phone calls', 'फ़ोन कॉल', 'फोन कॉल'), o('bells', 'Bells or announcements', 'घंटी या घोषणाएँ', 'घंटा किंवा घोषणा'), o('caregiving', 'Children or caregiving', 'बच्चे या देखभाल', 'मुले किंवा काळजी'), o('other', 'Other', 'अन्य', 'इतर')] },
      { id: 'comprehension_score', q: 'C3', sec: 'C', type: 'scale', required: true, scale: SCALE,
        en: 'How well did respondents understand the questions?', hi: 'उत्तरदाताओं ने प्रश्न कितनी अच्छी तरह समझे?', mr: 'उत्तरदात्यांना प्रश्न किती चांगले समजले?',
        anchors: { en: ['Very poorly', 'Very well'], hi: ['बहुत कम', 'बहुत अच्छी तरह'], mr: ['खूप कमी', 'खूप चांगले'] } },
      { id: 'items_reexplained', q: 'C4', sec: 'C', type: 'itemlist', required: false, min: 1, max: 200,
        en: 'Which question numbers needed repeated explanation?', hi: 'किन प्रश्न संख्याओं को बार-बार समझाना पड़ा?', mr: 'कोणत्या प्रश्न क्रमांकांना पुन्हा समजावावे लागले?' },
      { id: 'hostility', q: 'C5', sec: 'C', type: 'single', required: true,
        en: 'Was there resistance or hostility?', hi: 'क्या विरोध या शत्रुता थी?', mr: 'विरोध किंवा शत्रुत्व होते का?',
        options: [o('none', 'None', 'नहीं', 'नाही'), o('mild', 'Mild', 'हल्का', 'सौम्य'), o('strong', 'Strong', 'तीव्र', 'तीव्र')] },
      { id: 'objections', q: 'C6', sec: 'C', type: 'multi', required: true, exclusive: 'none',
        en: 'Objections raised', hi: 'उठाई गई आपत्तियाँ', mr: 'उपस्थित केलेले आक्षेप',
        options: [o('none', 'None', 'कोई नहीं', 'काहीही नाही'), o('purpose', 'Purpose of survey', 'सर्वे का उद्देश्य', 'सर्वेक्षणाचा उद्देश'), o('privacy', 'Privacy', 'गोपनीयता', 'गोपनीयता'), o('sensitive', 'Topic too sensitive', 'विषय बहुत संवेदनशील', 'विषय खूप संवेदनशील'), o('length', 'Too long', 'बहुत लंबा', 'खूप लांब'), o('cultural', 'Cultural or religious', 'सांस्कृतिक या धार्मिक', 'सांस्कृतिक किंवा धार्मिक'), o('other', 'Other', 'अन्य', 'इतर')] },
      { id: 'answer_sharing', q: 'C7', sec: 'C', type: 'single', required: true,
        en: 'Did respondents discuss or copy answers?', hi: 'क्या उत्तरदाताओं ने उत्तरों पर चर्चा की या नकल की?', mr: 'उत्तरदात्यांनी उत्तरांवर चर्चा केली किंवा नक्कल केली का?',
        options: [o('no', 'No', 'नहीं', 'नाही'), o('few', 'A few', 'कुछ ने', 'काहींनी'), o('many', 'Many', 'कई ने', 'अनेकांनी')] },
      { id: 'engagement_score', q: 'C8', sec: 'C', type: 'scale', required: true, scale: SCALE,
        en: 'Engagement level', hi: 'भागीदारी का स्तर', mr: 'सहभागाची पातळी',
        anchors: { en: ['Disengaged', 'Fully engaged'], hi: ['उदासीन', 'पूरी तरह शामिल'], mr: ['उदासीन', 'पूर्णपणे सहभागी'] } },
      { id: 'desirability_score', q: 'D1', sec: 'D', type: 'scale', required: true, scale: SCALE,
        en: 'Did people seem to give answers they thought we wanted?', hi: 'क्या लोग वह उत्तर देते लगे जो उन्हें लगा हम सुनना चाहते हैं?', mr: 'आम्हाला हवी असतील अशी उत्तरे लोक देत आहेत असे वाटले का?',
        anchors: { en: ['Not at all', 'Strongly'], hi: ['बिल्कुल नहीं', 'बहुत अधिक'], mr: ['अजिबात नाही', 'खूप जास्त'] } },
      { id: 'authority_influence', q: 'D2', sec: 'D', type: 'single', required: true,
        en: 'Did anyone in authority appear to influence answers?', hi: 'क्या किसी अधिकारी व्यक्ति ने उत्तरों को प्रभावित किया लगा?', mr: 'अधिकारपदावरील कोणी उत्तरांवर प्रभाव टाकला असे वाटले का?',
        options: [o('no', 'No', 'नहीं', 'नाही'), o('possibly', 'Possibly', 'शायद', 'कदाचित'), o('clearly', 'Clearly', 'स्पष्ट रूप से', 'स्पष्टपणे')] },
      { id: 'facilitator_lead', q: 'D3', sec: 'D', type: 'single', required: true,
        en: 'Did you explain any question in a way that may have suggested an answer?', hi: 'क्या आपने कोई प्रश्न ऐसे समझाया जिससे उत्तर का संकेत मिला हो?', mr: 'तुम्ही एखादा प्रश्न असा समजावला का ज्यामुळे उत्तर सुचले असेल?',
        options: [o('no', 'No', 'नहीं', 'नाही'), o('possibly', 'Possibly', 'शायद', 'कदाचित'), o('yes', 'Yes', 'हाँ', 'हो')] },
      { id: 'disclosure', q: 'E1', sec: 'E', type: 'single', required: true,
        en: 'Did anyone disclose harm during or after the session?', hi: 'क्या सत्र के दौरान या बाद किसी ने नुकसान/हानि के बारे में बताया?', mr: 'सत्रादरम्यान किंवा नंतर कोणी हानीबद्दल सांगितले का?',
        help: { en: 'Record only that it happened. Never its content.', hi: 'केवल इतना दर्ज करें कि ऐसा हुआ। विवरण कभी नहीं।', mr: 'फक्त असे घडले एवढेच नोंदवा. तपशील कधीही नाही.' },
        options: [o('no', 'No', 'नहीं', 'नाही'), o('yes', 'Yes', 'हाँ', 'हो')] },
      { id: 'protocol_followed', q: 'E2', sec: 'E', type: 'single', required: false, requiredIf: { field: 'disclosure', equals: 'yes' }, showIf: { field: 'disclosure', equals: 'yes' },
        en: 'Was the disclosure protocol followed?', hi: 'क्या प्रकटीकरण प्रोटोकॉल का पालन हुआ?', mr: 'प्रकटीकरण प्रोटोकॉल पाळला गेला का?',
        options: [o('yes', 'Yes', 'हाँ', 'हो'), o('partly', 'Partly', 'आंशिक रूप से', 'अंशतः'), o('no', 'No', 'नहीं', 'नाही')] },
      { id: 'help_requests_band', q: 'E3', sec: 'E', type: 'single', required: true,
        en: 'How many people asked for help or contact details afterwards?', hi: 'बाद में कितने लोगों ने मदद या संपर्क जानकारी माँगी?', mr: 'नंतर किती लोकांनी मदत किंवा संपर्क माहिती मागितली?',
        options: [o('0', '0', '0', '0'), o('1-2', '1–2', '1–2', '1–2'), o('3-5', '3–5', '3–5', '3–5'), o('6+', '6 or more', '6 या अधिक', '6 किंवा अधिक')] },
      { id: 'data_confidence', q: 'F1', sec: 'F', type: 'single', required: true,
        en: 'How much do you trust the data from this session?', hi: 'इस सत्र के डेटा पर आपको कितना भरोसा है?', mr: 'या सत्राच्या डेटावर तुमचा किती विश्वास आहे?',
        options: [o('high', 'High', 'अधिक', 'जास्त'), o('medium', 'Medium', 'मध्यम', 'मध्यम'), o('low', 'Low', 'कम', 'कमी')] },
      { id: 'stood_out', q: 'F2', sec: 'F', type: 'text', required: false,
        en: 'What stood out, good or bad?', hi: 'क्या ख़ास लगा, अच्छा या बुरा?', mr: 'काय लक्षात राहिले, चांगले किंवा वाईट?' },
      { id: 'next_facilitator', q: 'F3', sec: 'F', type: 'text', required: false,
        en: 'What should the next facilitator at this site know?', hi: 'इस जगह अगले फैसिलिटेटर को क्या पता होना चाहिए?', mr: 'या ठिकाणच्या पुढच्या फॅसिलिटेटरला काय माहीत असावे?' },
      { id: 'contradicts', q: 'F4', sec: 'F', type: 'text', required: false,
        en: 'Did anything you saw contradict what the numbers may show?', hi: 'क्या आपने कुछ ऐसा देखा जो आँकड़ों से उलट हो सकता है?', mr: 'तुम्ही पाहिलेले काही आकड्यांच्या विरोधात जाऊ शकते का?' }
    ],
    ui: {
      title: { en: 'Facilitator session note', hi: 'फैसिलिटेटर सत्र नोट', mr: 'फॅसिलिटेटर सत्र नोंद' },
      noNames: { en: 'No names, phone numbers or details that could identify anyone.', hi: 'कोई नाम, फ़ोन नंबर या पहचान बताने वाली जानकारी नहीं।', mr: 'कोणतेही नाव, फोन नंबर किंवा ओळख पटवणारी माहिती नको.' },
      submit: { en: 'Submit note', hi: 'नोट जमा करें', mr: 'नोंद जमा करा' },
      saved: { en: 'Saved. It will sync when you are online.', hi: 'सहेजा गया। ऑनलाइन होने पर सिंक होगा।', mr: 'जतन केले. ऑनलाइन आल्यावर सिंक होईल.' },
      fixErrors: { en: 'Please fix the highlighted answers.', hi: 'कृपया चिह्नित उत्तर ठीक करें।', mr: 'कृपया चिन्हांकित उत्तरे दुरुस्त करा.' },
      siteMemory: { en: 'Notes from earlier facilitators at this site', hi: 'इस जगह के पिछले फैसिलिटेटरों के नोट', mr: 'या ठिकाणच्या आधीच्या फॅसिलिटेटरच्या नोंदी' }
    }
  };
})();
if (typeof module !== 'undefined') { module.exports = FN_SCHEMA; }
